version: '3.8'
services:
    nestjs-api-casino:
        image: casino-image
        ports:
            - '8001:8001'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
        networks:
            - app_net
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        networks:
            - app_net
networks:
    app_net:
        driver: bridge
