version: '3.8'
services:
  k10-app:
    image: registry.gitlab.com/tranhuunam23022000/k10-be
    ports:
      - '9001:9001'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app_net
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
